### ISSUE TITLE
Remember my username and domian

### ISSUE THREAD

**Issue by jbltcuk** [Tohaker/mickgeorge-scraper#1]
**Is your feature request related to a problem? Please describe.**
I have to keep entering the username and domain. 

also show button is not working properly. when you hit show, it tries to login. 

**Describe the solution you'd like**
Can you save my entry information like google does so i don't have to keep entering it.

**Comment by Tohaker** [comment]
This issue has been fixed in [v1.3.1](https://github.com/Tohaker/mickgeorge-scraper/releases/tag/v1.3.1).
